<?php
/**
 * Verify the SigV4 signer against signatures produced by botocore.
 *
 *     docker compose cp dev/test-aws-sigv4.php wpcli:/tmp/tsig.php
 *     docker compose cp dev/aws-sigv4-vectors.json wpcli:/tmp/vec.json
 *     docker compose exec -T wpcli wp eval-file /tmp/tsig.php
 *
 * This exists because a hand-written signer cannot otherwise be told apart
 * from a broken one. Every mistake -- a header out of order, a path segment
 * encoded twice, the wrong region in the key chain -- surfaces as the same
 * opaque "SignatureDoesNotMatch" from AWS, and only once somebody has handed
 * over credentials.
 *
 * The vectors in aws-sigv4-vectors.json were generated by botocore, the
 * signing implementation AWS itself ships, over the request shapes this app
 * actually sends: a form-encoded query service, a JSON service, a URL with
 * query parameters, and a request carrying a session token. Each vector pins
 * the timestamp botocore used, so the comparison is deterministic.
 *
 * Regenerating them (only needed if the request shapes change):
 *
 *     python3 -m venv .venv && .venv/bin/pip install botocore
 *     .venv/bin/python <the generator in the commit that added this file>
 *
 * If these pass, a signing failure against the live API is a credential or
 * IAM permission problem, not this code -- which is the whole point of having
 * them.
 *
 * @package VulnHub
 */

if ( ! defined( 'WP_CLI' ) || ! WP_CLI ) {
	exit( "Run this through wp-cli - see the header for the docker compose cp/exec pair.\n" );
}

$path = '/tmp/vec.json';

if ( ! is_readable( $path ) ) {
	exit( "Missing {$path} - copy dev/aws-sigv4-vectors.json into the container first.\n" );
}

$vectors = json_decode( (string) file_get_contents( $path ), true );

if ( ! is_array( $vectors ) || ! $vectors ) {
	exit( "Could not read the vectors file.\n" );
}

$fails = 0;

echo "signatures must match botocore, byte for byte:\n";

foreach ( $vectors as $v ) {
	$got = VulnHub_AWS_SigV4::headers(
		(string) $v['method'],
		(string) $v['url'],
		(string) $v['body'],
		(array) $v['headers'],
		(string) $v['region'],
		(string) $v['service'],
		'AKIDEXAMPLE',
		'wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY',
		(string) $v['token'],
		(string) $v['stamp']
	);

	$ours  = (string) ( $got['Authorization'] ?? '' );
	$theirs = (string) $v['auth'];
	$ok    = $ours === $theirs;

	printf( "  [%s] %s\n", $ok ? ' ok ' : 'FAIL', (string) $v['name'] );

	if ( ! $ok ) {
		printf( "         botocore: %s\n         ours    : %s\n", $theirs, $ours );
		$fails++;
	}
}

printf( "\n%s\n", 0 === $fails ? 'All checks passed.' : $fails . ' check(s) FAILED.' );
